import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar/Navbar';
import StoreProvider from './StoreProvider';
import { cookies } from 'next/headers';
import { jwtVerify } from 'jose';
import StateJwt from '@/components/StateJwt';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
interface JwtPayload {
  id: number;
  role: number;
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const refreshtoken = cookieStore.get('refreshtoken')?.value as string;
  let role: number = 1;
  if (refreshtoken) {
    try {
      const { payload } = await jwtVerify(
        refreshtoken,
        new TextEncoder().encode(process.env.REFRESH_SECRET_KEY!)
      );
      const decoded = payload as unknown as JwtPayload;
      console.log('Decoded JWT payload:', decoded);
      role = decoded.role;
    } catch (err) {
      console.error('JWT verify error:', err);
    }
  }
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <StateJwt role={role} />
          <div className="sticky top-0 z-50 bg-white shadow">
            <Navbar />
          </div>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
