import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar/Navbar';
import StoreProvider from './StoreProvider';

import StateJwt from '@/components/StateJwt';
import { jwt } from '@/lib/jwt';
import { Toaster } from 'sonner';
import Notification from '@/components/notification/Notification';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const role = await jwt();
  console.log(role);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <StateJwt role={role} />
          <div className="sticky top-0 z-50 bg-white shadow">
            <Navbar />
          </div>
          {children}
          <Toaster />
          <Notification />
        </StoreProvider>
      </body>
    </html>
  );
}
